[tool.poetry]
name = "rorf"
version = "0.1.0"
description = ""
authors = ["Tze-Yang Tung <r0ymanesco@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
